language: node_js

node_js:
  - "10"

cache:
  directories:
    - projects/cell-builder/node_modules
    - projects/cell-cid/node_modules
    - projects/cell-codecs/node_modules
    - projects/cell-pb/node_modules
    - projects/runtime/node_modules
    - projects/synaptic-types/node_modules
    - projects/typescript-cell/node_modules
    - projects/util/node_modules

script:
 - cd projects/cell-builder && npm install && npm test
 - cd projects/cell-cid && npm install && npm test
 - cd projects/cell-codecs && npm install && npm test
 - cd projects/cell-pb && npm install && npm test
 - cd projects/runtime && npm install && npm test
 - cd projects/synaptic-types && npm install && npm test
 - cd projects/typescript-cell && npm install && npm test
 - cd projects/util && npm install && npm test
